"""init

Revision ID: 68b9fcdbe6a6
Revises: 
Create Date: 2026-03-07 13:14:49.176340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68b9fcdbe6a6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_short_url'), table_name='links')
    op.drop_table('links')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('short_url', sa.VARCHAR(length=6), nullable=False),
    sa.Column('original_url', sa.VARCHAR(length=2048), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('clicks', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('short_url')
    )
    op.create_index(op.f('ix_links_short_url'), 'links', ['short_url'], unique=False)
    # ### end Alembic commands ###
